### ISSUE TITLE
running code

### ISSUE THREAD

**Issue by ynieWXJB** [alterzero/DBPN-caffe#2]
Could anyone give me some guidance on how to run the code in caffe environment? 

I have tried several times. But it did not give me any results.

Thanks a lot!

**Comment by alterzero** [comment]
Have you installed the matcaffe? if yes, then you just need to run DBPN_main_rgb.m

**Comment by ynieWXJB** [comment]
Thanks for your message.

I only installed caffe. I will try matcaffe later.

**Comment by alterzero** [comment]
You must run 'make matcaffe' first to enable MATLAB wrapper. Then, you can use caffe from MATLAB

**Comment by Gchinanty** [comment]
I have installed matcaffe. And I have downloaded pretrained models.
But after I run DBPN_main_rgb.m at the root of DBPN-caffe which I have directly downloaded from GitHub. I only get the following results:
Bi cubic: NaN , NaN , NaN , NaN
dbpn: NaN , NaN , NaN , NaN
What's the matter with what l did? And could you tell me how I can get the correct results?
Thanks!!!
